# Generated by Django 5.1.4 on 2024-12-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author_clap_author_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='clap',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
