# Generated by Django 5.1.5 on 2025-01-29 08:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.IntegerField(default=accounts.models.get_random_price),
        ),
    ]
